name: KimuuSchedule
options:
  bundleIdPrefix: com.kimuu
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  KimuuSchedule:
    type: application
    platform: iOS
    sources:
      - path: KimuuSchedule
    settings:
      base:
        INFOPLIST_FILE: KimuuSchedule/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.kimuu.schedule
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Supabase
        product: Supabase
    info:
      path: KimuuSchedule/Resources/Info.plist
      properties:
        CFBundleName: "KIMUU Schedule"
        CFBundleDisplayName: "KIMUU"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

schemes:
  KimuuSchedule:
    build:
      targets:
        KimuuSchedule: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
